name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save pjmtix    
      - run: kubectl apply -f infra/k8s
